env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "fast-web-419215-35d284e06546.json"

service: superfest-api
runtime: python311

instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: automatic
  max_idle_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80

# Enable App Engine APIs
app_engine_apis: false

handlers:
- url: /.*
  script: auto
  login: optional
  secure: always

# Specify the request timeout
runtime_config:
  request_timeout: 300