env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "fast-web-419215-35d284e06546.json"

service: superfest-api
runtime: python311

runtime_config:
  request_timeout: 300

instance_class: B2

# Specify the maximum number of instances for basic scaling
basic_scaling:
  max_instances: 1
  idle_timeout: 4m
